# Day10 Assignment09 Submitted by Mr. Dileep Kumar Kadali
## Assistant Professor, CSE Department,
### Swarnandhra College of Engineering and Technology (A2)


# Assignment questions for Numpy

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the size of any array (★☆☆)

In [4]:
len(arr)

10

#### 5. Create a null vector of size 10(★☆☆)

In [5]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
arr2 = 10 + np.arange(40)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
mat1 = np.arange(9).reshape(3,3)
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix (★☆☆)

In [8]:
mat2 = np.eye(3)
mat2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Create a 3x3x3 array with random values (★☆☆)

In [9]:
mat3 = np.random.random((3,3,3))
mat3

array([[[0.00700536, 0.48841449, 0.26118256],
        [0.30956146, 0.51221308, 0.66957886],
        [0.78464147, 0.04074595, 0.31387006]],

       [[0.17666207, 0.78587686, 0.89934883],
        [0.40374487, 0.99750945, 0.49323676],
        [0.39354818, 0.50349564, 0.70404063]],

       [[0.35911143, 0.61341735, 0.06247944],
        [0.87104658, 0.02188433, 0.21447983],
        [0.315571  , 0.88708266, 0.62706987]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
mat4 = np.random.random((10,10))
print(mat4)
print("Minimum Value: ",mat4.min())
print("Maximum Value: ",mat4.max())

[[0.09550466 0.15516656 0.8256204  0.86649362 0.89897011 0.30101909
  0.02792868 0.14827827 0.77040547 0.5604639 ]
 [0.76049241 0.57086501 0.24683796 0.23579698 0.96320662 0.19262228
  0.77415204 0.08947424 0.16477885 0.59577519]
 [0.16375576 0.94843693 0.07674579 0.79475758 0.51287711 0.27436836
  0.41541163 0.6919867  0.7651867  0.99351376]
 [0.54626856 0.5862311  0.64712907 0.79285269 0.13001088 0.04771931
  0.72771217 0.11487526 0.66824352 0.62872685]
 [0.8475104  0.01954812 0.06949305 0.31569645 0.77002793 0.38827242
  0.37987686 0.70341971 0.2889185  0.09028726]
 [0.7606313  0.5499436  0.53400474 0.03500798 0.64893849 0.20441256
  0.9261975  0.73624453 0.48868293 0.03443399]
 [0.3498769  0.71781221 0.62737401 0.73396962 0.70819556 0.20201975
  0.70837692 0.98273131 0.56795932 0.86264535]
 [0.54723264 0.83465473 0.49565089 0.4022984  0.57999564 0.03674929
  0.29736871 0.63157032 0.53501693 0.57436142]
 [0.09078652 0.25293868 0.54315272 0.01637138 0.68154536 0.05655124
  0.38239339

#### 11. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
arr3 = np.random.random(10)
arr3.mean()

0.5222451051031707

#### 12. Create a 2d array (★☆☆)

In [12]:
arr4 = np.array([[3, 2, 9], [5, 6, 4]], np.int32)
print(arr4)
print(arr4.shape)

[[3 2 9]
 [5 6 4]]
(2, 3)


#### 13. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
M1 = np.random.random((5,3))
print("First array:")
print(M1)
M2 = np.random.random((3,2))
print("Second array:")
print(M2)
Mprod = np.dot(M1, M2)
print("Product of two arrays(M1XM2):")
print(Mprod)

First array:
[[0.84505059 0.37591042 0.41868341]
 [0.85413894 0.67043149 0.62119968]
 [0.76610793 0.98971817 0.41080958]
 [0.77443481 0.38109348 0.28763421]
 [0.88568177 0.70468849 0.10215434]]
Second array:
[[0.4701459  0.93492698]
 [0.12556484 0.16416079]
 [0.65416707 0.495983  ]]
Product of two arrays(M1XM2):
[[0.7183871  1.0594302 ]
 [0.89212091 1.21672058]
 [0.7531944  1.08248245]
 [0.60011011 0.92926228]
 [0.57170975 0.99439681]]


#### 14. Create a 5X5 array with random values and compute statistics such as mean,med,std and var

In [14]:
mat5 = np.random.random((5,5))
print("Original Array:")
print(mat5) 
mat5_min, mat5_max = mat5.min(), mat5.max()
print("Minimum Value= {} and Maximum Value= {}".format(mat5_min, mat5_max))


Original Array:
[[0.76373547 0.54073886 0.45777154 0.4692462  0.58679176]
 [0.87807232 0.03479953 0.08379369 0.89618207 0.24778688]
 [0.38644009 0.60220443 0.01440574 0.75762195 0.74563378]
 [0.1749396  0.63979681 0.0779871  0.78685794 0.34202513]
 [0.53621027 0.99562315 0.89045156 0.01390288 0.25542206]]
Minimum Value= 0.013902877327997332 and Maximum Value= 0.9956231546128761


#### 15. Convert below statement to lowercase and first letter to upper case

"Am I learning new from these python sessions ?"

In [15]:
str="Am I learning new from these python sessions ?"
print(str)
print(str.lower())
str1=str.capitalize()
print(str1)


Am I learning new from these python sessions ?
am i learning new from these python sessions ?
Am i learning new from these python sessions ?


#### 16. Convert your response (for above question)  to upper case

In [16]:
str1.upper()

'AM I LEARNING NEW FROM THESE PYTHON SESSIONS ?'

#### 17. Create 4X4 array and combine another 2X4 array vertically

In [17]:
Mat_A = np.arange(0,16).reshape(4,4)
Mat_B = np.arange(16,24).reshape(2,4)
print("Matrix-1: ")
print(Mat_A)
print("Matrix-2: ")
print(Mat_B)
print("Matrix- Concatenate Horizonatally: ")
Mat_C=np.concatenate((Mat_A,Mat_B))
print(Mat_C)
print("Matrix Concatenate Vertically: ")
print(np.vstack((Mat_A.T, Mat_B)).T)

Matrix-1: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Matrix-2: 
[[16 17 18 19]
 [20 21 22 23]]
Matrix- Concatenate Horizonatally: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Matrix Concatenate Vertically: 
[[ 0  1  2  3 16 20]
 [ 4  5  6  7 17 21]
 [ 8  9 10 11 18 22]
 [12 13 14 15 19 23]]
